### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by dzad** [JonTvermose/UnityARCore#1]
hello,
i'm new to unity 
i want to start a new AR project, but i can't understand what should i do? should i modify the hello AR project? 
or start a new one? if it is the case where is your scripts in this project i can't figure them out.
please help me.

**Comment by JonTvermose** [comment]
Hi dzad,

If you're just starting out with AR and Unity, I would recommend you to read this: https://developers.google.com/ar/develop/unity/getting-started

You are also welcome to clone this repository and use it as a base for your own project.
If you want to run this project, you should open and build the scene located in _Assets/GoogleARCore/HelloARExample/Scenes/HelloAR_
Just make sure to setup your ARCore-compitable phone as described in https://developers.google.com/ar/develop/unity/getting-started :-)

**Comment by dzad** [comment]
thank you.
